---
development:
  dialect: "sqlite3"
  database: C:\Users\alexey.i\go\tic-tac-toe__api_tic_tac_toe_api_development.sqlite

test:
  dialect: "sqlite3"
  database: C:\Users\alexey.i\go\tic-tac-toe__api_tic_tac_toe_api_test.sqlite

production:
  dialect: "sqlite3"
  database: C:\Users\alexey.i\go\tic-tac-toe__api_tic_tac_toe_api_production.sqlite
